main: body.Main
name: Napoleon
version: 1.0
author: Robert Chen
description: A plugin that simulates Napoleonic era troop formations.
commands:
  fire:
    description: Commands currently selected troops to shoot.
    usage: /fire
    permission: myplugin.fire
    permission-message: You don't have permission to fire.